/**
 * Writes each deployable contract's ABI + creation bytecode to packages/core/src/abi/
 * so the web app can deploy and call it. Run after `hardhat compile`:
 *   npx hardhat run scripts/export-abi.ts
 * Contract tests fail if an exported file drifts from the compiled artifact.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const CONTRACTS = [
  { name: 'PrismCrystal', file: 'prismCrystal.ts', id: 'prismCrystal' },
  { name: 'PrismForgeRouter', file: 'prismForgeRouter.ts', id: 'prismForgeRouter' },
];

const outDir = path.join(__dirname, '../../packages/core/src/abi');
mkdirSync(outDir, { recursive: true });
for (const c of CONTRACTS) {
  const art = JSON.parse(readFileSync(path.join(__dirname, `../artifacts/contracts/${c.name}.sol/${c.name}.json`), 'utf8'));
  const body = `// GENERATED by contracts/scripts/export-abi.ts — do not edit by hand.
// Source: contracts/contracts/${c.name}.sol (solc 0.8.24, optimizer 200 runs, evm cancun)

export const ${c.id}Abi = ${JSON.stringify(art.abi, null, 2)} as const;

export const ${c.id}Bytecode = '${art.bytecode}' as const;
`;
  writeFileSync(path.join(outDir, c.file), body);
  console.log('wrote', path.join(outDir, c.file), `(${(art.bytecode.length - 2) / 2} bytes init code)`);
}
