/**
 * Writes PrismCrystal's ABI + creation bytecode to packages/core/src/abi/prismCrystal.ts
 * so the web app can deploy and call it. Run after `hardhat compile`:
 *   npx hardhat run scripts/export-abi.ts
 * A contracts test fails if the exported file drifts from the compiled artifact.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const art = JSON.parse(
  readFileSync(path.join(__dirname, '../artifacts/contracts/PrismCrystal.sol/PrismCrystal.json'), 'utf8'),
);
const outDir = path.join(__dirname, '../../packages/core/src/abi');
mkdirSync(outDir, { recursive: true });
const body = `// GENERATED by contracts/scripts/export-abi.ts — do not edit by hand.
// Source: contracts/contracts/PrismCrystal.sol (solc 0.8.24, optimizer 200 runs, evm cancun)

export const prismCrystalAbi = ${JSON.stringify(art.abi, null, 2)} as const;

export const prismCrystalBytecode = '${art.bytecode}' as const;
`;
writeFileSync(path.join(outDir, 'prismCrystal.ts'), body);
console.log('wrote', path.join(outDir, 'prismCrystal.ts'), `(${(art.bytecode.length - 2) / 2} bytes init code)`);
